### ISSUE TITLE
como atualiza o cid10?

### ISSUE THREAD

**Issue by robertveloso** [Atiladanvi/cid-api#6]
Gostei muito do projeto, poderia compartilhar a forma você utiliza para atualizar o cid10.json?

**Comment by a21ns1g4ts** [comment]
Cada versão do cid possui uma lista fixa de patologias, não sendo passíveis de atualizações. Quando a OMS atualiza a lista ela lança uma nova edição. Na história já tivemos o cid9 e o cid10. Em 2018 a oms começou a trabalhar na atualização da lista de doenças. A previsão é que essa edição seja lançada oficialmente em 2022, até lá esse json continua sendo o referencial médico para o enquadramento de doenças com o código.  Quando sair o cid11 pretendo forkar esse repo e disponibilizar uma api com a atualização.

**Comment by robertveloso** [comment]
Entendi agora, eu estava confundindo com a tabela de procidimentos do sigtap. Acabei achando outro projeto interessante para unificar os dados dos procedimentos: https://github.com/rdsilva/SIGTAP
Estou tentando criar uma api dos procedimentos em nodejs, se tiver algo a mais sobre o assunto e tiver interesse em ajudar me dá um toque robertluizveloso@gmail.com.
No mais agradeço!
